import 'package:flutter_test/flutter_test.dart';
import 'package:journal_app/l10n/app_localizations.dart';
import 'package:journal_app/l10n/app_localizations_en.dart';
import 'package:journal_app/l10n/app_localizations_tr.dart';

List<Object> _touchAll(AppLocalizations l10n) {
  final values = <Object>[];
  values.add(l10n.appTitle);
  values.add(l10n.profileSettingsTitle);
  values.add(l10n.settingsTitle);
  values.add(l10n.appearanceTitle);
  values.add(l10n.themeModeTitle);
  values.add(l10n.themeSystem);
  values.add(l10n.themeLight);
  values.add(l10n.themeDark);
  values.add(l10n.accountTitle);
  values.add(l10n.signOut);
  values.add(l10n.signOutConfirmTitle);
  values.add(l10n.signOutConfirmMessage);
  values.add(l10n.cancel);
  values.add(l10n.aboutTitle);
  values.add(l10n.version);
  values.add(l10n.licenses);
  values.add(l10n.loading);
  values.add(l10n.errorPrefix);
  values.add(l10n.copyUsernameSuccess);
  values.add(l10n.copyUsernameTooltip);
  values.add(l10n.language);
  values.add(l10n.languageSystem);
  values.add(l10n.languageTurkish);
  values.add(l10n.languageEnglish);
  values.add(l10n.onboardingTitleCaptureMemories);
  values.add(l10n.onboardingDescCaptureMemories);
  values.add(l10n.onboardingTitleShareTogether);
  values.add(l10n.onboardingDescShareTogether);
  values.add(l10n.onboardingTitlePersonalize);
  values.add(l10n.onboardingDescPersonalize);
  values.add(l10n.onboardingSkip);
  values.add(l10n.onboardingNext);
  values.add(l10n.onboardingGetStarted);
  values.add(l10n.loginTagline);
  values.add(l10n.loginProfileChecking);
  values.add(l10n.loginGoogleSignIn);
  values.add(l10n.loginAppleSignIn);
  values.add(l10n.loginAccountExistsWithGoogleTitle);
  values.add(l10n.loginAccountExistsWithGoogleMessage);
  values.add(l10n.loginContinueWithGoogle);
  values.add(l10n.loginCanLinkAppleLater);
  values.add(l10n.loginAppleIOSOnly);
  values.add(l10n.loginAppleMissingToken);
  values.add(l10n.loginAppleInvalidCredential);
  values.add(l10n.loginGoogleConfigError);
  values.add(l10n.loginFirebaseUnavailable);
  values.add(l10n.linkedAccountsTitle);
  values.add(l10n.linkedProviderGoogle);
  values.add(l10n.linkedProviderApple);
  values.add(l10n.linkedStatusConnected);
  values.add(l10n.linkedStatusNotConnected);
  values.add(l10n.linkAppleAction);
  values.add(l10n.linkAppleSuccess);
  values.add(l10n.linkAppleUnsupported);
  values.add(l10n.linkAppleNeedsRecentLogin);
  values.add(l10n.linkAppleAlreadyLinked);
  values.add(l10n.linkAppleCredentialInUse);
  values.add(l10n.editorTooltipShare);
  values.add(l10n.editorTooltipPreview);
  values.add(l10n.editorTooltipSave);
  values.add(l10n.editorPdfPreparing);
  values.add(l10n.editorExportPdf);
  values.add(l10n.editorSaved);
  values.add(l10n.editorToolSelect);
  values.add(l10n.editorToolText);
  values.add(l10n.editorToolDraw);
  values.add(l10n.editorToolErase);
  values.add(l10n.editorToolMedia);
  values.add(l10n.editorToolSticker);
  values.add(l10n.editorToolTag);
  values.add(l10n.editorToolZoomReset);
  values.add(l10n.editorToolRotate);
  values.add(l10n.editorToolFrame);
  values.add(l10n.editorToolDelete);
  values.add(l10n.editorMediaAdd);
  values.add(l10n.editorMediaImage);
  values.add(l10n.editorMediaImageSubtitle);
  values.add(l10n.editorMediaVideo);
  values.add(l10n.editorMediaVideoSubtitle);
  values.add(l10n.editorMediaAudio);
  values.add(l10n.editorMediaAudioSubtitle);
  values.add(l10n.editorMediaDrawing);
  values.add(l10n.editorMediaDrawingSubtitle);
  values.add(l10n.editorVideoFromGallery);
  values.add(l10n.editorVideoFromCamera);
  values.add(l10n.editorPageTags);
  values.add(l10n.editorEraserSize);
  values.add(l10n.editorTextPlaceholder);
  values.add(l10n.editorMicPermissionRequired);
  values.add(l10n.editorFrameSelect);
  values.add(l10n.editorFrameNone);
  values.add(l10n.editorFrameRound);
  values.add(l10n.editorFrameRounded);
  values.add(l10n.editorFramePolaroid);
  values.add(l10n.editorFrameTape);
  values.add(l10n.editorFrameShadow);
  values.add(l10n.editorFrameFilm);
  values.add(l10n.editorFrameStacked);
  values.add(l10n.editorFrameSticker);
  values.add(l10n.editorFrameBorder);
  values.add(l10n.editorFrameGradient);
  values.add(l10n.editorFrameVintage);
  values.add(l10n.editorFrameLayered);
  values.add(l10n.editorFrameTapeCorner);
  values.add(l10n.editorFramePolaroidClassic);
  values.add(l10n.editorFrameVintageEdge);
  values.add(l10n.editorDeleteBlockTitle);
  values.add(l10n.editorDeleteBlockMessage);
  values.add(l10n.editorDelete);
  values.add(l10n.editorRotateImageTitle);
  values.add(l10n.editorApply);
  values.add(l10n.editorUnsavedTitle);
  values.add(l10n.editorUnsavedMessage);
  values.add(l10n.editorExitWithoutSave);
  values.add(l10n.editorSaveAndExit);
  values.add(l10n.editorPageTitle(1));
  values.add(l10n.editorSaveLocalCloudFail('err'));
  values.add(l10n.editorRecordError('err'));
  values.add(l10n.editorCurrentAngle(1));
  values.add(l10n.editorErrorWithMessage('err'));
  return values;
}

void main() {
  test('touches all english localization getters and methods', () {
    final values = _touchAll(AppLocalizationsEn());
    expect(values.length, greaterThan(90));
    expect(values.first, isNotEmpty);
  });

  test('touches all turkish localization getters and methods', () {
    final values = _touchAll(AppLocalizationsTr());
    expect(values.length, greaterThan(90));
    expect(values.first, isNotEmpty);
  });
}
