// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkZf16b0yp5oJ6lpKHWngS-IPKePvEU6c',
    appId: '1:317674243768:web:c2ad1b75fbe70dcfa0d64d',
    messagingSenderId: '317674243768',
    projectId: 'journal-cf6d7',
    authDomain: 'journal-cf6d7.firebaseapp.com',
    storageBucket: 'journal-cf6d7.firebasestorage.app',
    measurementId: 'G-1DYWJRD1L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAudM5Rjf61sY-V-DPx8klh1LiMZQKcdUg',
    appId: '1:317674243768:android:c98a4dc02a3a8c96a0d64d',
    messagingSenderId: '317674243768',
    projectId: 'journal-cf6d7',
    storageBucket: 'journal-cf6d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXp6nN4h5dGpa5uf7SEZDGkDUxnu1sZbY',
    appId: '1:317674243768:ios:aeee8ccc32d3882fa0d64d',
    messagingSenderId: '317674243768',
    projectId: 'journal-cf6d7',
    storageBucket: 'journal-cf6d7.firebasestorage.app',
    androidClientId:
        '317674243768-ldc0pr0p5odtkr750jkb2jq3stg8geic.apps.googleusercontent.com',
    iosClientId:
        '317674243768-d01a007ul3ta3djjlre1h0b7q2s0f3gt.apps.googleusercontent.com',
    iosBundleId: 'com.bgirginn.journalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXp6nN4h5dGpa5uf7SEZDGkDUxnu1sZbY',
    appId: '1:317674243768:ios:aeee8ccc32d3882fa0d64d',
    messagingSenderId: '317674243768',
    projectId: 'journal-cf6d7',
    storageBucket: 'journal-cf6d7.firebasestorage.app',
    androidClientId:
        '317674243768-ldc0pr0p5odtkr750jkb2jq3stg8geic.apps.googleusercontent.com',
    iosClientId:
        '317674243768-d01a007ul3ta3djjlre1h0b7q2s0f3gt.apps.googleusercontent.com',
    iosBundleId: 'com.bgirginn.journalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkZf16b0yp5oJ6lpKHWngS-IPKePvEU6c',
    appId: '1:317674243768:web:9b897767f6f36b04a0d64d',
    messagingSenderId: '317674243768',
    projectId: 'journal-cf6d7',
    authDomain: 'journal-cf6d7.firebaseapp.com',
    storageBucket: 'journal-cf6d7.firebasestorage.app',
    measurementId: 'G-SC8REJ8TTG',
  );
}
